# Generated by Django 5.0.4 on 2024-04-25 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.curso'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='nombre',
            field=models.PositiveBigIntegerField(),
        ),
    ]
